apiVersion: v1
kind: Service
metadata:
  name: bare-metal-ssh
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: bare-metal-ssh
  namespace: default
  labels:
    kubernetes.io/service-name: bare-metal-ssh
addressType: IPv4
ports:
  - name: ssh
    port: 22
    protocol: TCP
endpoints:
  - addresses:
      - PLACEHOLDER_IP
